@rootURL = http://localhost:5107

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/books
Accept: application/json

###

GET {{rootURL}}/api/books/2
Accept: application/json

###

POST {{rootURL}}/api/books
Content-Type: application/json
{
    "ID": 5,
    "Title": "Queen of Sorcery (The Belgariad, Book 2)",
    "Author": "David Eddings",
    "YearPublished": 1982,
}