@rootURL = http://localhost:5107

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/books
Accept: application/json

###

GET {{rootURL}}/api/books/2
Accept: application/json

###

POST {{rootURL}}/api/books
Content-Type: application/json
{
    "ID": 5,
    "Title": "Queen of Sorcery (The Belgariad, Book 2)",
    "Author": "David Eddings",
    "YearPublished": 1982,
}

###

PUT {{rootURL}}/api/books/4
Content-Type: application/json
{
    "ID": 4,
    "Title": "Wizard's First Rule (The Legend of the Seeker of Truth)",
    "Author": "Me",
    "YearPublished": 1995,
}